site_name: Summary of Self-Help books
site_url: https://learn-with-me.github.io/books-self-help/
repo_url: https://github.com/learn-with-me/books-self-help
docs_dir: 'src'
draft_docs: 'book-name/'               # A "drafts" directory anywhere.

theme:
  name: material
  logo: assets/images/logo.png
#   favicon: assets/images/favicon.ico
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
  palette: 

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    # - navigation.sections
    - navigation.indexes
    - navigation.top
    # - toc.integrate
  plugins:
    - tags
extra:
  homepage: https://learn-with-me.github.io/books-self-help/
  copyright: Copyright &copy; 2023 - 2024 goel4ever
  analytics:
    provider: google
    property: G-CDR2H1HJZ8
